### ISSUE TITLE
REF and CAT tables are not of the same length

### ISSUE THREAD

**Issue by PK0207** [deepspace-ucsb/sdi_pipeline#115] opened 2021-08-10 11:59 UTC
**Describe the bug**

**To Reproduce**
1. Ran `sdi read -d /home/pkotta/GTAnd_SCI/ align extract -w CAT 1 subtract extract ref write -d /home/pkotta/sditest_output/` on 08/07/21
2. Check the lengths of the output REF and CAT tables in a python terminal or however you wish.
3. Check the difference between the lengths of the table in each fits file
4. See screenshot below for the result from this run.

**Expected behavior**
The lengths of the tables should be the same.

**Screenshots**
![image](https://user-images.githubusercontent.com/30590837/128867361-28999078-c380-42b1-bec6-1d52fbb607ad.png)
![image](https://user-images.githubusercontent.com/30590837/128916090-d8b49e03-fc8c-4302-a244-bde1ef5f073d.png)

**Desktop (please complete the following information):**
- When was SDI last pulled - 08/10/21
**Additional context**
I believe that ref outputs differences differently every time. I will run the script again with the first 5-10 of the same images and check for the differences again. EDIT: This is true. For the same first ten images, the differences do not match up (regardless of how glob jumbles things up). See second screenshot.

**Comment by EdgarMao** [comment] 2021-10-13 06:40
A quick note about an improtant problem with ref.py:

The threshold used for determining the size of the GAIA cone search (line 72-74 in norm_sources) and determining if the sources in GAIA and CAT match (line 95 in norm_sources) is the same variable. This should definitely not be the case, using the same variable here does not make sense. This might be a big part of the reason why ref.py has been giving strange results. (I have a fix for this problem that is being tested, will send a PR soon). This problem is also the cause of this issue, so fixing this, i.e. finding an adequate threshold for both the cone search and the matching of sources, would likely both solve this issue, and improve the performance of ref.py.

**Comment by EdgarMao** [comment] 2021-11-01 23:47
Current State of my fix for ref.py:

So far, my fix of ref.py now contains a better coversion method for RA and Dec of the soruces, and a proper way of thresholding, however there is still clearly a significant loss of sources in the REF table:

 - The images I used for testing my fix for ref.py is from the file `small_data`, for these images there are about 370-380 sources in their CAT table, and my fix for ref.py consistently (unlike the previous version, this fix produces the same amount of sources in REF for the same image every time, and REF is always shorter than CAT) produces around 230-280 sources in REF for most of the images (only 1 out of the 10 I tested had 209 sources).
 - I conducted a manual check (manually entering the RA/DEC of the source into the GAIA manual search website) for a couple of randomly selected sources in ref.py, I am fairly certain that the sources that are found by ref.py are real sources that are consistent with their corresponding sources in CAT.
 - The REF and CAT table's difference in length is still considered problematic since GAIA in principle should contain a more complete collection of sources than LCO, however, I am no longer sure if this is purely an issue with ref.py, because so far I am having trouble finding more potential issues strictly within ref.py. This leads me to suspect that there might be some upstream issues, like uncertainties in source extractor or other uncertainties in our observations, however, I have not found any concrete problems yet.

Given the current situation, I believe the best way to further investigate this problem is to attempt to conduct light curve analysis with the output of my version of ref.py, and if the light curve produced does make sense, then there would be a good reason to believe that ref.py is now functioning, and the lost sources are due to some upstream issues; if the result does not make sense, this issue will remain open.

@PK0207 What do you think about this idea? Is it possible for you to show me how to convert the flux of sources to magnitude and construct light curves? If the result is still messy like your previous results then ref.py probably still needs some change.

**Comment by PK0207** [comment] 2021-11-02 00:46
Stuff to get started : -

Next step:
- Get coordinates transform merged in
Tests:
- length of zeros (number of sources not found)
- transformed magnitudes and compare to CAT (scatter plot on the same axes)
- Plot a lightcurve for a background star

**Comment by EdgarMao** [comment] 2021-11-07 02:10
The following is a plot of the locations of the catalog sources (the green dots) and the soures in REF (the blue plus signs). On the left hand side of this picture is the code used to make this plot and some information about the fits file used.

![Screenshot 2021-11-06 190735](https://user-images.githubusercontent.com/31234107/140629660-0c124a2c-2bd7-4ea7-95e7-c913d0e24406.png)

So far it seems like ref.py may not be icking up the correct sources using CAT, I will be looking into the way we transfer coordinates, and also adding x and y coordinates to REF table.

**Comment by PK0207** [comment] 2021-11-07 02:39
Could be worth making the cone radius of search smaller as we get closer to the edge. Masking removes edge effect I think.

Check that the reference frames are the same.

**Comment by EdgarMao** [comment] 2021-11-15 01:15
Current State of ref.py and its connection with issue #132:

My debugging process has revealed that the problem of this issue seems to be an emergent phenomenon due to a couple of problems in different parts of the pipeline. I have made my best attempt to ensure that ref.py itself functions as intended, and the changes I made to the script is recorded in the comments above. However, the changes in ref.py alone cannot fix this issue because:

 - Like mentioned in issue #132, due to the use of astroalign (a method that does not change the header data of the fits file), the x,y values extracted by the pipeline are not correctly related with their header information. This means that we will not be able to correctly transform their xy coordinates on the image with their ra and dec.

 - Also, as a quick attempt to circumnavigate this problem, I tried running ref without any prior programs, and simply use the CAT table we get from our original fits files. However, the sources between the images still don't match up. So far I am not sure if this is due to potential flaws in my method for checking if the sources matched up, or problems with external things like noises and so on.

Will update this after I figure out if my way of checking is reliable.

**Comment by PK0207** [comment] 2021-12-26 06:58
From updates to Alignment and ref, the CAT table seems to be consistently larger than the REF table. This is what we expect because there might be some sources that could not be found in the gaia database, but are in our catalogs, but given the nature of our query (coordinate matching) there cannot be sources from gaia that are not found in CAT.

I then reversed the query. Using RA DEC information from REF, I look for the same ra values in the cat table, and find the corresponding x and y values. Will improve to query using both ra and dec.

I am doing this check to ensure that the sources we found in the gaia query are indeed the same sources from the CAT table. Since I checked that the CAT table sources were indeed real sources by cross-checking with SIMBAD catalogs, this means gaia has been finding real sources, and the astrometry process is successful.

**Closed as completed** 2022-02-09 17:28 UTC
